/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/untitled.gltf
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useCharacterAnimations } from "../contexts/CharacterAnimations";

const Kich = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/Plane4.gltf')
  const { setAnimations, animationIndex } = useCharacterAnimations();
  const { actions, names } = useAnimations(animations, group)
  console.log(names);
  useEffect(() => {
    setAnimations(names);
  }, [names]);

  useEffect(() => {
    actions[names[animationIndex]].reset().fadeIn(0.5).play();
    return () => {
      actions[names[animationIndex]].fadeOut(0.5);
    };
  }, [animationIndex]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="fuselage01" geometry={nodes.fuselage01.geometry} material={materials.base} position={[0, 1.27, 2.87]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh name="rudder01" geometry={nodes.rudder01.geometry} material={materials.base} position={[6.02, 0, -0.04]}>
            <mesh name="rudder02" geometry={nodes.rudder02.geometry} material={materials.base} position={[0.08, 0, -0.08]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
              <mesh name="pin06" geometry={nodes.pin06.geometry} material={materials.base} position={[0.06, 0, 0]} rotation={[0, -1.57, 0]}>
                <mesh name="rudder03" geometry={nodes.rudder03.geometry} material={materials.base} position={[0.03, 0, 0]} rotation={[0, 1.57, 0]}>
                  <mesh name="rudder_wire_L" geometry={nodes.rudder_wire_L.geometry} material={materials.base} rotation={[1.67, -0.01, 1.52]}>
                    <mesh name="pin07001" geometry={nodes.pin07001.geometry} material={materials.base} position={[0.03, 0, 0]} rotation={[0, 0.01, 1.59]} />
                  </mesh>
                </mesh>
              </mesh>
              <mesh name="pin06001" geometry={nodes.pin06001.geometry} material={materials.base} position={[-0.06, 0, 0]} rotation={[0, -1.57, 0]}>
                <mesh name="rudder04" geometry={nodes.rudder04.geometry} material={materials.base} position={[0.03, 0, 0]} rotation={[0, 1.57, 0]}>
                  <mesh name="rudder_wire_R" geometry={nodes.rudder_wire_R.geometry} material={materials.base} rotation={[1.67, 0.01, 1.62]}>
                    <mesh name="pin07" geometry={nodes.pin07.geometry} material={materials.base} position={[0.03, 0, 0]} rotation={[0, 0, 1.59]} />
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
            <mesh name="undercarriage_tail02" geometry={nodes.undercarriage_tail02.geometry} material={materials.internals_alu} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
              <mesh name="rudder_spring_L" geometry={nodes.rudder_spring_L.geometry} material={materials.internals_alu} position={[0.05, -0.02, -0.01]} rotation={[-0.29, 0, 3.13]} scale={[0.92, 0.92, 1.17]}>
                <group name="undercarriage_tail_track_L02" position={[0.01, 0, -0.11]} rotation={[-0.47, 0.03, -3.12]} scale={[1.42, 1.03, 0.92]} />
              </mesh>
              <mesh name="rudder_spring_R" geometry={nodes.rudder_spring_R.geometry} material={materials.internals_alu} position={[-0.05, -0.02, -0.01]} rotation={[-0.46, -0.05, -3.13]} scale={[1.07, 1.07, 0.88]}>
                <group name="undercarriage_tail_track_R02" position={[0, 0, -0.1]} rotation={[-0.52, 0.03, -3.14]} scale={[1.33, 1, 1]} />
              </mesh>
            </mesh>
          </mesh>
          <group name="rudder_track_L" position={[5.56, 0.08, -0.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <group name="rudder_track_R01" position={[5.56, -0.08, -0.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh name="engine01" geometry={nodes.engine01.geometry} material={materials.internals_b} position={[-0.1, 0, 0.04]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh name="engine02" geometry={nodes.engine02.geometry} material={materials.internals_alu} position={[-0.2, 0, 0.04]} rotation={[0, 0, Math.PI / 2]} />
          <mesh name="engine03" geometry={nodes.engine03.geometry} material={materials.internals_alu} position={[-0.2, 0, 0.28]} rotation={[0, 0, Math.PI / 2]} />
          <mesh name="engine04" geometry={nodes.engine04.geometry} material={materials.internals_alu} position={[-0.2, -0.09, 0.32]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh name="engine05" geometry={nodes.engine05.geometry} material={materials.internals_b} position={[-0.07, 0, 0.04]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh name="engine06" geometry={nodes.engine06.geometry} material={materials.internals_alu} position={[-0.07, 0, 0.04]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh name="engine07" geometry={nodes.engine07.geometry} material={materials.internals_alu} position={[-0.07, -0.01, 0.04]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh name="engine08" geometry={nodes.engine08.geometry} material={materials.internals_b} position={[-0.07, -0.01, 0.04]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh name="exhaust" geometry={nodes.exhaust.geometry} material={materials.internals_alu} position={[0.43, -0.18, 0.44]} rotation={[0.37, -1.35, Math.PI / 2]} />
          <mesh name="fuselage02" geometry={nodes.fuselage02.geometry} material={materials.base}>
            <group name="prop_tip01" position={[-0.48, 0, 0.04]} rotation={[-1.99, 0, Math.PI / 2]}>
              <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.base} />
              <mesh name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials.prop} />
              <mesh name="prop01" geometry={nodes.prop01.geometry} material={materials.prop} position={[0, -0.2, 0]} rotation={[-Math.PI / 2, 0, 0.37]} />
              <mesh name="prop02" geometry={nodes.prop02.geometry} material={materials.prop} position={[0, -0.2, 0]} rotation={[-Math.PI / 2, 0, -2.77]} />
              <mesh name="prop_tip02" geometry={nodes.prop_tip02.geometry} material={materials.base} position={[0, -0.22, 0]} rotation={[0, Math.PI / 4, 0]} />
            </group>
            <mesh name="fuselage_lock01001" geometry={nodes.fuselage_lock01001.geometry} material={materials.base} position={[0, 0.3, 0.29]} rotation={[2.36, -1.36, 1.51]}>
              <mesh name="fuselage_lock02001" geometry={nodes.fuselage_lock02001.geometry} material={materials.internals_alu} position={[0.04, 0, 0]} rotation={[0, 0, -0.27]}>
                <mesh name="pin02-1001" geometry={nodes['pin02-1001'].geometry} material={materials.internals_alu} position={[0.05, 0, 0]}>
                  <mesh name="pin02-2" geometry={nodes['pin02-2'].geometry} material={materials.internals_alu} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                </mesh>
              </mesh>
            </mesh>
            <mesh name="fuselage_lock01002" geometry={nodes.fuselage_lock01002.geometry} material={materials.base} position={[0.38, -0.35, 0.35]} rotation={[0.76, 1.37, 1.73]}>
              <mesh name="fuselage_lock02003" geometry={nodes.fuselage_lock02003.geometry} material={materials.internals_alu} position={[0.04, 0, 0]} rotation={[0, 0, -0.21]}>
                <mesh name="pin02-1003" geometry={nodes['pin02-1003'].geometry} material={materials.internals_alu} position={[0.05, 0, 0]}>
                  <mesh name="pin02-2003" geometry={nodes['pin02-2003'].geometry} material={materials.internals_alu} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                </mesh>
              </mesh>
            </mesh>
            <mesh name="fuselage_lock01003" geometry={nodes.fuselage_lock01003.geometry} material={materials.base} position={[0, -0.3, 0.29]} rotation={[0.8, 1.38, 1.5]}>
              <mesh name="fuselage_lock02002" geometry={nodes.fuselage_lock02002.geometry} material={materials.internals_alu} position={[0.04, 0, 0]} rotation={[0, 0, -0.27]}>
                <mesh name="pin02-1002" geometry={nodes['pin02-1002'].geometry} material={materials.internals_alu} position={[0.05, 0, 0]}>
                  <mesh name="pin02-2002" geometry={nodes['pin02-2002'].geometry} material={materials.internals_alu} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                </mesh>
              </mesh>
            </mesh>
            <mesh name="fuselage_lock01" geometry={nodes.fuselage_lock01.geometry} material={materials.base} position={[0.38, 0.35, 0.35]} rotation={[2.36, -1.35, 1.71]}>
              <mesh name="fuselage_lock02" geometry={nodes.fuselage_lock02.geometry} material={materials.internals_alu} position={[0.04, 0, 0]} rotation={[0, 0, -0.21]}>
                <mesh name="pin02-1" geometry={nodes['pin02-1'].geometry} material={materials.internals_alu} position={[0.05, 0, 0]}>
                  <mesh name="pin02-2001" geometry={nodes['pin02-2001'].geometry} material={materials.internals_alu} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                </mesh>
              </mesh>
            </mesh>
          </mesh>
          <mesh name="fuselage03" geometry={nodes.fuselage03.geometry} material={materials.base}>
            <mesh name="engine09" geometry={nodes.engine09.geometry} material={materials.internals_b} position={[-0.01, 0, 0.45]} rotation={[0, 0.15, Math.PI / 2]}>
              <mesh name="engine10" geometry={nodes.engine10.geometry} material={materials.internals_b} position={[0, 0.07, 0]} />
            </mesh>
            <mesh name="fuselage04" geometry={nodes.fuselage04.geometry} material={materials.base} />
            <mesh name="fuselage05" geometry={nodes.fuselage05.geometry} material={materials.base} />
            <mesh name="fuselage06" geometry={nodes.fuselage06.geometry} material={materials.base} />
          </mesh>
          <mesh name="fuselage07" geometry={nodes.fuselage07.geometry} material={materials.base} position={[-0.18, 0, 0.3]} />
          <mesh name="fuselage08" geometry={nodes.fuselage08.geometry} material={materials.base} position={[1.37, 0, -0.35]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh name="fuselage09" geometry={nodes.fuselage09.geometry} material={materials.base} position={[1.78, 0, -0.76]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh name="fuselage10" geometry={nodes.fuselage10.geometry} material={materials.base} />
          <mesh name="fuselage11" geometry={nodes.fuselage11.geometry} material={materials.base} />
          <mesh name="fuselage12" geometry={nodes.fuselage12.geometry} material={materials.base} position={[1.17, -0.32, 0.6]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh name="undercarriage_R05" geometry={nodes.undercarriage_R05.geometry} material={materials.base} position={[0.05, -0.01, 0]} rotation={[Math.PI, 0, 2.24]} />
          </mesh>
          <mesh name="fuselage13" geometry={nodes.fuselage13.geometry} material={materials.base} position={[1.17, 0.32, 0.6]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh name="undercarriage_L05" geometry={nodes.undercarriage_L05.geometry} material={materials.base} position={[-0.05, -0.01, 0]} rotation={[0, 0, -0.91]} />
          </mesh>
          <mesh name="fuselage14" geometry={nodes.fuselage14.geometry} material={materials.base} position={[1.71, -0.32, 0.6]} rotation={[1.58, 0, -Math.PI / 2]} />
          <mesh name="fuselage15" geometry={nodes.fuselage15.geometry} material={materials.base} position={[1.71, 0.32, 0.6]} rotation={[1.56, 0, Math.PI / 2]} />
          <mesh name="fuselage16" geometry={nodes.fuselage16.geometry} material={materials.base} position={[5.57, 0.1, -0.06]} rotation={[-1.05, -1.43, -1.2]} />
          <mesh name="fuselage_door" geometry={nodes.fuselage_door.geometry} material={materials.base} />
          <mesh name="fuselage_door02" geometry={nodes.fuselage_door02.geometry} material={materials.base} />
          <mesh name="fuselage_wings" geometry={nodes.fuselage_wings.geometry} material={materials.base} position={[1.71, 0, -0.7]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh name="aileron_L01" geometry={nodes.aileron_L01.geometry} material={materials.base} position={[3.49, -0.04, -0.67]}>
              <mesh name="aileron_L02" geometry={nodes.aileron_L02.geometry} material={materials.base} position={[-0.14, -0.08, -0.1]}>
                <mesh name="wing_wire_L02" geometry={nodes.wing_wire_L02.geometry} material={materials.base} position={[0, -0.04, 0.02]} rotation={[-0.16, -0.05, 1.56]} />
              </mesh>
              <mesh name="aileron_L03" geometry={nodes.aileron_L03.geometry} material={materials.base} position={[-0.14, 0.03, -0.1]} rotation={[-0.22, 0, 0]}>
                <mesh name="wing_wire_L03" geometry={nodes.wing_wire_L03.geometry} material={materials.base} rotation={[-0.01, 0, 1.57]} />
              </mesh>
            </mesh>
            <group name="aileron_track_L01" position={[3.36, 0.09, -0.35]} rotation={[1.36, 0, 0]} />
            <group name="aileron_track_L02" position={[3.33, -0.08, -0.19]} rotation={[1.4, 0, 0]} />
            <group name="aileron_track_R01" position={[-3.36, 0.09, -0.35]} rotation={[1.36, 0, 0]} />
            <group name="aileron_track_R02" position={[-3.33, -0.08, -0.19]} rotation={[1.4, 0, 0]} />
            <mesh name="aileron_L04" geometry={nodes.aileron_L04.geometry} material={materials.base} position={[3.36, 0.07, -0.4]} rotation={[-0.19, 0, 0]} />
            <mesh name="aileron_R04" geometry={nodes.aileron_R04.geometry} material={materials.base} position={[-3.36, 0.07, -0.4]} rotation={[-0.19, 0, 0]} />
            <mesh name="aileron_R01" geometry={nodes.aileron_R01.geometry} material={materials.base} position={[-3.49, -0.04, -0.67]} rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh name="aileron_R02" geometry={nodes.aileron_R02.geometry} material={materials.base} position={[-0.14, -0.08, 0.1]} rotation={[-Math.PI, 0, Math.PI]}>
                <mesh name="wing_wire_R02" geometry={nodes.wing_wire_R02.geometry} material={materials.base} position={[0, -0.04, 0.02]} rotation={[-0.16, 0.05, 1.58]} />
              </mesh>
              <mesh name="aileron_R03" geometry={nodes.aileron_R03.geometry} material={materials.base} position={[-0.14, 0.03, 0.1]} rotation={[0.22, 0, Math.PI]}>
                <mesh name="wing_wire_R03" geometry={nodes.wing_wire_R03.geometry} material={materials.base} rotation={[3.13, 0, 1.57]} />
              </mesh>
            </mesh>
            <mesh name="flap_L01" geometry={nodes.flap_L01.geometry} material={materials.base} position={[1.63, -0.12, -0.76]}>
              <mesh name="flap_L02" geometry={nodes.flap_L02.geometry} material={materials.base} position={[-0.8, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="pin01001" geometry={nodes.pin01001.geometry} material={materials.base} position={[0.01, -0.01, 0]} />
              </mesh>
              <mesh name="flap_L03" geometry={nodes.flap_L03.geometry} material={materials.base} position={[0.01, 0.01, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="pin01" geometry={nodes.pin01.geometry} material={materials.base} position={[0.01, -0.01, 0]} />
              </mesh>
            </mesh>
            <mesh name="flap_R01" geometry={nodes.flap_R01.geometry} material={materials.base} position={[-1.63, -0.12, -0.76]}>
              <mesh name="flap_R02" geometry={nodes.flap_R02.geometry} material={materials.base} position={[0.8, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="pin01002" geometry={nodes.pin01002.geometry} material={materials.base} position={[0.01, 0.01, 0]} />
              </mesh>
              <mesh name="flap_R03" geometry={nodes.flap_R03.geometry} material={materials.base} position={[-0.01, 0.01, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="pin01003" geometry={nodes.pin01003.geometry} material={materials.base} position={[0.01, 0.01, 0]} />
              </mesh>
            </mesh>
            <mesh name="wing_light_L01" geometry={nodes.wing_light_L01.geometry} material={materials.base} position={[5.13, 0, 0.41]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="wing_light_L02" geometry={nodes.wing_light_L02.geometry} material={materials.glass} />
              <mesh name="wing_light_L03" geometry={nodes.wing_light_L03.geometry} material={materials.mirror} position={[0, 0.05, 0]} />
            </mesh>
            <mesh name="wing_light_R01" geometry={nodes.wing_light_R01.geometry} material={materials.base} position={[-5.13, 0, 0.41]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="wing_light_R02" geometry={nodes.wing_light_R02.geometry} material={materials.glass} />
              <mesh name="wing_light_R03" geometry={nodes.wing_light_R03.geometry} material={materials.mirror} position={[0, 0.05, 0]} />
            </mesh>
          </mesh>
          <mesh name="fuselage_wings02" geometry={nodes.fuselage_wings02.geometry} material={materials.base} position={[1.71, 0, -0.7]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh name="horizontal_stab01" geometry={nodes.horizontal_stab01.geometry} material={materials.base} position={[5.69, 0, -0.32]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh name="elevator01" geometry={nodes.elevator01.geometry} material={materials.base} position={[0, 0.02, -0.27]} />
          </mesh>
          <mesh name="interior_frame01" geometry={nodes.interior_frame01.geometry} material={materials.internals_b} position={[1.39, 0, -0.72]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh name="interior_frame02" geometry={nodes.interior_frame02.geometry} material={materials.internals_b} position={[1.38, 0.31, -0.7]} rotation={[1.23, 0.6, -1.99]} />
          <mesh name="interior_frame03" geometry={nodes.interior_frame03.geometry} material={materials.internals_b} position={[1.38, -0.31, -0.7]} rotation={[1.31, -0.25, 0.89]} />
          <mesh name="interior_panel" geometry={nodes.interior_panel.geometry} material={materials.internals_b} position={[0.72, 0, -0.21]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh name="interior_seat" geometry={nodes.interior_seat.geometry} material={materials.internals_b} position={[1.18, 0, 0.36]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh name="pin03" geometry={nodes.pin03.geometry} material={materials.base} position={[5.87, 0.03, -0.89]} rotation={[2.12, Math.PI / 2, 0]}>
            <mesh name="rudder10" geometry={nodes.rudder10.geometry} material={materials.base} position={[0.01, 0, 0]}>
              <mesh name="wire_L01" geometry={nodes.wire_L01.geometry} material={materials.base} position={[0.04, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="rudder09" geometry={nodes.rudder09.geometry} material={materials.base} position={[0, 0.95, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
              </mesh>
            </mesh>
          </mesh>
          <mesh name="pin03001" geometry={nodes.pin03001.geometry} material={materials.base} position={[5.87, -0.03, -0.89]} rotation={[1.02, -Math.PI / 2, 0]}>
            <mesh name="rudder13" geometry={nodes.rudder13.geometry} material={materials.base} position={[0.01, 0, 0]}>
              <mesh name="wire_R01" geometry={nodes.wire_R01.geometry} material={materials.base} position={[0.04, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="rudder12" geometry={nodes.rudder12.geometry} material={materials.base} position={[0, 0.95, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
              </mesh>
            </mesh>
          </mesh>
          <mesh name="rudder05" geometry={nodes.rudder05.geometry} material={materials.internals_alu} position={[5.88, 0, -0.03]} rotation={[0, -1.42, Math.PI / 2]}>
            <mesh name="pin05" geometry={nodes.pin05.geometry} material={materials.base} position={[-0.08, 0.01, 0]} rotation={[2.99, 0, -2.79]}>
              <mesh name="rudder07" geometry={nodes.rudder07.geometry} material={materials.base} position={[0.01, 0, 0]}>
                <mesh name="wire_R02" geometry={nodes.wire_R02.geometry} material={materials.base} position={[0.04, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
                  <mesh name="rudder11" geometry={nodes.rudder11.geometry} material={materials.base} position={[0, 0.8, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]}>
                    <mesh name="pin04001" geometry={nodes.pin04001.geometry} material={materials.base} position={[0.01, 0.01, 0]} rotation={[0, 0, 0.35]} />
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
            <mesh name="pin05001" geometry={nodes.pin05001.geometry} material={materials.base} position={[0.08, 0.01, 0]} rotation={[-0.15, 0, 0.35]}>
              <mesh name="rudder06" geometry={nodes.rudder06.geometry} material={materials.base} position={[0.01, 0, 0]}>
                <mesh name="wire_L02" geometry={nodes.wire_L02.geometry} material={materials.base} position={[0.04, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
                  <mesh name="rudder08" geometry={nodes.rudder08.geometry} material={materials.base} position={[0, 0.8, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]}>
                    <mesh name="pin04" geometry={nodes.pin04.geometry} material={materials.base} position={[0.01, 0.01, 0]} rotation={[0, 0, 0.35]} />
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
          </mesh>
          <mesh name="rudder_frame01" geometry={nodes.rudder_frame01.geometry} material={materials.internals_alu} position={[6, 0, -0.04]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh name="rudder_frame02" geometry={nodes.rudder_frame02.geometry} material={materials.internals_alu} position={[6, 0, -0.05]} rotation={[0.02, -0.7, 1.32]} />
          <mesh name="rudder_frame03" geometry={nodes.rudder_frame03.geometry} material={materials.internals_alu} position={[6, 0, -0.05]} rotation={[-0.02, -0.7, 1.82]} />
          <mesh name="rudder_frame04" geometry={nodes.rudder_frame04.geometry} material={materials.internals_alu} position={[6, 0, -0.05]} rotation={[0.02, 0.12, 1.43]} />
          <mesh name="rudder_frame05" geometry={nodes.rudder_frame05.geometry} material={materials.internals_alu} position={[6, 0, -0.05]} rotation={[-0.02, 0.12, 1.71]} />
          <mesh name="undercarriage02" geometry={nodes.undercarriage02.geometry} material={materials.base} position={[1.18, 0, 0.83]} rotation={[0, 0, Math.PI / 2]}>
            <mesh name="undercarriage01" geometry={nodes.undercarriage01.geometry} material={materials.base} position={[0, 0.03, 0]}>
              <group name="undercarriage_L_pivot" position={[0.04, -0.01, 0]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="undercarriage_R_pivot" position={[-0.04, -0.01, 0]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh name="undercarriage_L03" geometry={nodes.undercarriage_L03.geometry} material={materials.base} position={[0.04, -0.01, 0]} rotation={[-Math.PI / 2, 0, 1.21]}>
                <mesh name="undercarriage_L04" geometry={nodes.undercarriage_L04.geometry} material={materials.base} position={[0, -0.26, 0]} rotation={[0, 0, -Math.PI / 2]} />
              </mesh>
              <mesh name="undercarriage_R03" geometry={nodes.undercarriage_R03.geometry} material={materials.base} position={[-0.04, -0.01, 0]} rotation={[Math.PI / 2, 0, -1.93]}>
                <mesh name="undercarriage_R04" geometry={nodes.undercarriage_R04.geometry} material={materials.base} position={[0, -0.26, 0]} rotation={[0, 0, -1.57]} />
              </mesh>
            </mesh>
          </mesh>
          <mesh name="undercarriage_L01" geometry={nodes.undercarriage_L01.geometry} material={materials.base} position={[1.17, 0.32, 0.6]} rotation={[-2.32, -Math.PI / 2, 0]}>
            <mesh name="undercarriage_L02" geometry={nodes.undercarriage_L02.geometry} material={materials.base} position={[-0.07, -0.56, 0]} rotation={[-3.14, 0, -0.47]} />
            <group name="wheel_L01" position={[0.1, -0.71, 0]} rotation={[Math.PI / 2, -0.75, 0]}>
              <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.tires} />
              <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.base} />
            </group>
            <mesh name="wheel_L02" geometry={nodes.wheel_L02.geometry} material={materials.internals_alu} position={[0.02, -0.64, 0]} rotation={[0, 0, -2.32]} />
            <mesh name="wheel_L03" geometry={nodes.wheel_L03.geometry} material={materials.internals_alu} position={[0.03, -0.66, 0]} rotation={[0, 0, -2.32]} />
          </mesh>
          <mesh name="undercarriage_R01" geometry={nodes.undercarriage_R01.geometry} material={materials.base} position={[1.17, -0.32, 0.6]} rotation={[-0.83, 1.57, 0]}>
            <mesh name="undercarriage_R02" geometry={nodes.undercarriage_R02.geometry} material={materials.base} position={[-0.07, -0.56, 0]} rotation={[3.14, 0, -0.47]} />
            <group name="wheel_R01" position={[0.1, -0.71, 0]} rotation={[-Math.PI / 2, 0.75, Math.PI]}>
              <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials.tires} />
              <mesh name="Plane022_1" geometry={nodes.Plane022_1.geometry} material={materials.base} />
              <mesh name="wheel_R02" geometry={nodes.wheel_R02.geometry} material={materials.internals_alu} position={[0.1, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
                <mesh name="wheel_R03" geometry={nodes.wheel_R03.geometry} material={materials.internals_alu} position={[0, 0.02, 0]} />
              </mesh>
            </group>
          </mesh>
          <mesh name="undercarriage_tail01" geometry={nodes.undercarriage_tail01.geometry} material={materials.internals_b} position={[5.9, 0, -0.01]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh name="undercarriage_tail03" geometry={nodes.undercarriage_tail03.geometry} material={materials.internals_alu} position={[0, -0.02, -0.11]} rotation={[-0.28, 0, 0]}>
              <mesh name="undercarriage_tail04" geometry={nodes.undercarriage_tail04.geometry} material={materials.internals_alu} position={[0, 0, -0.2]} rotation={[0.42, 0, 0]}>
                <mesh name="undercarriage_tail05" geometry={nodes.undercarriage_tail05.geometry} material={materials.internals_alu} position={[0, -0.01, -0.01]} rotation={[Math.PI / 2, 0, 0]}>
                  <group name="undercarriage_tail_track_L01" position={[0.06, 0, -0.02]} rotation={[-1.57, 0, 0]} scale={[1.33, 1, 1]}>
                    <mesh name="undercarriage_tail_wire_L02" geometry={nodes.undercarriage_tail_wire_L02.geometry} material={materials.internals_alu} position={[0, 0, 0.01]} rotation={[-0.51, -0.03, 1.56]} scale={[1.32, 0.75, 1.02]}>
                      <mesh name="undercarriage_wire_L01" geometry={nodes.undercarriage_wire_L01.geometry} material={materials.internals_alu} position={[0, 0, 0.01]} rotation={[0, 0, Math.PI / 2]} />
                    </mesh>
                  </group>
                  <group name="undercarriage_tail_track_R01" position={[-0.06, 0, -0.02]} rotation={[-1.57, 0, 0]} scale={[1.33, 1, 1]}>
                    <mesh name="undercarriage_tail_wire_R02" geometry={nodes.undercarriage_tail_wire_R02.geometry} material={materials.internals_alu} position={[0, 0, 0.01]} rotation={[-0.51, 0.03, 1.58]} scale={[1.32, 0.75, 1.02]}>
                      <mesh name="undercarriage_tail_wire_R01" geometry={nodes.undercarriage_tail_wire_R01.geometry} material={materials.internals_alu} position={[0, 0, 0.01]} rotation={[0, 0, Math.PI / 2]} />
                    </mesh>
                  </group>
                  <group name="wheel_tail01" position={[0, -0.09, 0.09]} rotation={[-1.57, 0, -Math.PI / 2]}>
                    <mesh name="Cylinder013" geometry={nodes.Cylinder013.geometry} material={materials.tires} />
                    <mesh name="Cylinder013_1" geometry={nodes.Cylinder013_1.geometry} material={materials.internals_alu} />
                  </group>
                </mesh>
              </mesh>
            </mesh>
          </mesh>
          <mesh name="windshield01" geometry={nodes.windshield01.geometry} material={materials.glass} />
          <mesh name="windshield02" geometry={nodes.windshield02.geometry} material={materials.glass} />
          <mesh name="wing_support_L01" geometry={nodes.wing_support_L01.geometry} material={materials.base} position={[1.72, 0.35, 0.57]} rotation={[-Math.PI / 2, -1.43, 0.38]}>
            <mesh name="nut01002" geometry={nodes.nut01002.geometry} material={materials.base} position={[0.09, 0, 0.03]} rotation={[3.05, 0.24, -1.55]}>
              <mesh name="wing_support_L09" geometry={nodes.wing_support_L09.geometry} material={materials.base} position={[0, -0.02, 0]} />
            </mesh>
            <mesh name="nut01003" geometry={nodes.nut01003.geometry} material={materials.base} position={[0.09, 0, -0.01]} rotation={[-3.14, 0, -Math.PI / 2]}>
              <mesh name="wing_support_L08" geometry={nodes.wing_support_L08.geometry} material={materials.base} position={[0, -0.02, 0]} />
            </mesh>
            <mesh name="wing_support_L05" geometry={nodes.wing_support_L05.geometry} material={materials.base}>
              <mesh name="wing_support_L02" geometry={nodes.wing_support_L02.geometry} material={materials.base} position={[1.53, 0.05, 0.17]} rotation={[1.53, -0.05, 0.13]} />
              <mesh name="wing_support_L03" geometry={nodes.wing_support_L03.geometry} material={materials.base} position={[1.51, 0.08, 0.36]} rotation={[0.2, -0.22, -0.34]}>
                <mesh name="wing_support_L11" geometry={nodes.wing_support_L11.geometry} material={materials.base} position={[0, 0.53, 0]} rotation={[-0.27, 0, -Math.PI / 2]} />
              </mesh>
              <mesh name="wing_support_L04" geometry={nodes.wing_support_L04.geometry} material={materials.base} position={[1.55, 0.06, -0.01]} rotation={[-0.36, 0, -0.4]}>
                <mesh name="wing_support_L10" geometry={nodes.wing_support_L10.geometry} material={materials.base} position={[0, 0.54, 0]} rotation={[0.34, 0, -Math.PI / 2]} />
              </mesh>
            </mesh>
            <mesh name="wing_support_L06" geometry={nodes.wing_support_L06.geometry} material={materials.base} position={[3.08, 0.03, 0.72]} rotation={[-0.05, -0.13, -0.38]}>
              <mesh name="aileron_controll_L01" geometry={nodes.aileron_controll_L01.geometry} material={materials.base} position={[-0.02, -0.01, -0.01]} rotation={[Math.PI / 2, 0.37, -Math.PI]}>
                <mesh name="aileron_controll_L02" geometry={nodes.aileron_controll_L02.geometry} material={materials.base} position={[0.06, 0.08, 0]} rotation={[-Math.PI / 2, Math.PI / 4, 0]}>
                  <mesh name="aileron_controll_L03" geometry={nodes.aileron_controll_L03.geometry} material={materials.base} position={[0, 0, -0.04]} />
                  <mesh name="aileron_controll_L04" geometry={nodes.aileron_controll_L04.geometry} material={materials.base} position={[0, 0, 0.03]}>
                    <mesh name="aileron_controll_L05" geometry={nodes.aileron_controll_L05.geometry} material={materials.base} />
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
            <mesh name="wing_support_L07" geometry={nodes.wing_support_L07.geometry} material={materials.base} position={[3.17, 0, -0.01]} rotation={[-0.05, -0.13, -0.38]}>
              <mesh name="pin08" geometry={nodes.pin08.geometry} material={materials.base} position={[-0.02, -0.01, 0]} rotation={[Math.PI / 2, 0.37, -Math.PI]} />
            </mesh>
            <mesh name="wing_wire_L01" geometry={nodes.wing_wire_L01.geometry} material={materials.base} position={[0.04, 0.02, -0.03]} rotation={[-0.05, -0.13, -0.38]} />
          </mesh>
          <mesh name="wing_support_R01" geometry={nodes.wing_support_R01.geometry} material={materials.base} position={[1.72, -0.35, 0.57]} rotation={[-Math.PI / 2, 1.43, -2.76]}>
            <mesh name="nut01" geometry={nodes.nut01.geometry} material={materials.base} position={[-0.09, 0, -0.03]} rotation={[3.05, 0.24, -1.55]}>
              <mesh name="wing_support_R09" geometry={nodes.wing_support_R09.geometry} material={materials.base} position={[0, 0.02, 0]} />
            </mesh>
            <mesh name="nut01001" geometry={nodes.nut01001.geometry} material={materials.base} position={[-0.09, 0, 0.01]} rotation={[-3.14, 0, -Math.PI / 2]}>
              <mesh name="wing_support_R08" geometry={nodes.wing_support_R08.geometry} material={materials.base} position={[0, 0.02, 0]} />
            </mesh>
            <mesh name="wing_support_R05" geometry={nodes.wing_support_R05.geometry} material={materials.base}>
              <mesh name="wing_support_R02" geometry={nodes.wing_support_R02.geometry} material={materials.base} position={[-1.53, -0.05, -0.17]} rotation={[1.53, -0.05, 0.13]} />
              <mesh name="wing_support_R03" geometry={nodes.wing_support_R03.geometry} material={materials.base} position={[-1.51, -0.08, -0.36]} rotation={[0.2, -0.22, -0.34]}>
                <mesh name="wing_support_R11" geometry={nodes.wing_support_R11.geometry} material={materials.base} position={[0, -0.53, 0]} rotation={[-0.27, 0.01, -Math.PI / 2]} scale={-1} />
              </mesh>
              <mesh name="wing_support_R04" geometry={nodes.wing_support_R04.geometry} material={materials.base} position={[-1.55, -0.06, 0.01]} rotation={[-0.36, 0, -0.4]}>
                <mesh name="wing_support_R10" geometry={nodes.wing_support_R10.geometry} material={materials.base} position={[0, -0.54, 0]} rotation={[0.34, 0.01, -Math.PI / 2]} scale={-1} />
              </mesh>
            </mesh>
            <mesh name="wing_support_R06" geometry={nodes.wing_support_R06.geometry} material={materials.base} position={[-3.08, -0.03, -0.72]} rotation={[-0.05, -0.13, -0.38]}>
              <mesh name="aileron_controll_R01" geometry={nodes.aileron_controll_R01.geometry} material={materials.base} position={[0.02, 0.01, 0.01]} rotation={[Math.PI / 2, 0.37, -Math.PI]}>
                <mesh name="aileron_controll_R02" geometry={nodes.aileron_controll_R02.geometry} material={materials.base} position={[-0.06, -0.08, 0]} rotation={[-Math.PI / 2, Math.PI / 4, 0]}>
                  <mesh name="aileron_controll_R03" geometry={nodes.aileron_controll_R03.geometry} material={materials.base} position={[0, 0, 0.04]} />
                  <mesh name="aileron_controll_R04" geometry={nodes.aileron_controll_R04.geometry} material={materials.base} position={[0, 0, -0.03]}>
                    <mesh name="aileron_controll_R05" geometry={nodes.aileron_controll_R05.geometry} material={materials.base} />
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
            <mesh name="wing_support_R07" geometry={nodes.wing_support_R07.geometry} material={materials.base} position={[-3.17, 0, 0.01]} rotation={[-0.05, -0.13, -0.38]}>
              <mesh name="pin08001" geometry={nodes.pin08001.geometry} material={materials.base} position={[0.02, 0.01, 0]} rotation={[Math.PI / 2, 0.37, -Math.PI]} />
            </mesh>
            <mesh name="wing_wire_R01" geometry={nodes.wing_wire_R01.geometry} material={materials.base} position={[-0.04, -0.02, 0.03]} rotation={[-0.05, -0.13, -0.38]} />
          </mesh>
        </mesh>
      </group>
    </group>
  )
}

export default Kich;

useGLTF.preload('./models/Kich.gltf')
